_target_: pp2023.model.linear.Linear
n_time_models: 12
n_variables: 2
share_member: True
share_station: True
share_step: True
share_time: True
embedding_member: False
embedding_station: False
embedding_step: False
embedding_time: False
use_metadata_features: True