_target_: pp2023.model.linear.Linear
n_time_models: 12
n_variables: ${ex.n_variables}
share_member: True
share_station: False
share_step: False
share_time: True
share_forecast_time: True
use_metadata_features: True
use_step_feature: True
use_spatial_features: True
use_forecast_time_feature: True