_target_: pp2023.model.mlp.MLP
embedding_size: 256
n_blocks: 4
use_station_embedding: true
use_step_embedding: true
use_step_feature: true
embedding_activation: false
use_metadata_features: true
use_spatial_features: true
use_batch_norm: true
use_forecast_time_feature: true
use_forecast_embedding: false
use_model_version_feature: false