_target_: pp2023.model.mlp.SimpleMLP
embedding_size: 256
n_hidden_layers: 4
use_station_embedding: true
use_step_embedding: true
use_step_feature: true
use_metadata_features: true
use_spatial_features: true
use_forecast_time_feature: false
use_forecast_time_embedding: true 