defaults:
- _self_
- ex: ens10_metar_emos
- mlflow: dev
- optional site: ${oc.env:DL93_SITE,""}

hydra:
  run:
    dir: ${oc.env:PP2023_RUN_DIR,"."}/run/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:PP2023_RUN_DIR,"."}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True


num_workers: ${oc.decode:${oc.env:SLURM_CPUS_PER_TASK,4}}

pre: # Dict of preprocessing external commands, empty for now.

ex:
  jz_constraint: 
  qos: