defaults:
- _self_
- ex: ens10_metar_emos
- mlflow: dev
- optional site: ${oc.env:DL93_SITE,""}

hydra:
  run:
    dir: ${oc.env:PP2023_RUN_DIR,"."}/run/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:PP2023_RUN_DIR,"."}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True


num_workers: 6

pre: # Dict of preprocessing external commands, empty for now.

ex:
  jz_constraint: 
  qos:
  # Bring some choices here to make them easier to visualize in mlflow.
  distribution_name: ${hydra:runtime.choices.ex/distribution}
  model_name: ${hydra:runtime.choices.ex/model}
  dataset_name: ${hydra:runtime.choices.ex/dataset}

seed: 11347
limit_dataset:
conda_env_name: pp2023