n_parameters: 16  # For every forecast, we need 4 parameters to initialize our distributions.
mapping:
  _target_: pp2023.distribution.mapping.ConstructiveQuantileMapping
  n_quantiles: ${..n_parameters}