n_parameters: 32  # For every forecast, we need 4 parameters to initialize our distributions.
strategy:
  _target_: pp2023.distribution.base.AdditiveQuantileRegressionStrategy
  n_quantiles: ${..n_parameters}
  loss: crps