defaults:
- dataset: pp2023_medium
- nwp: ens10
- model: transformer
- distribution: quantile
- optimizer: adam
- scheduler: one_cycle
- _self_

timeout_min: 1200

batch_size: 64
max_epochs: 1000 
log_every_n_steps: 20
early_stopping_patience: 800

# optimizer:
#   lr: 1e-3

distribution:
  n_parameters: 32

dataset:
  n_features: 32

scheduler:
  instance:
    max_lr: 5e-4
    pct_start: 0.15
    final_div_factor: 100

jz_constraint: v100-32g