defaults:
- dataset: ens10_metar_steps_station_subset
- nwp: ens10
- model: emos
- distribution: normal
- optimizer: adam
- scheduler: reduce_lr_plateau
- _self_

timeout_min: 60

batch_size: 64
max_epochs: 300
log_every_n_steps: 1
early_stopping_patience: 50

optimizer:
  lr: 1e-3