defaults:
- dataset: gdps_prebatch_24h
- model: mlp
- distribution: normal
- optimizer: adam
- scheduler: reduce_lr_plateau
- _self_

timeout_min: 1200

batch_size:  # Use prebatched dataset.
max_epochs: 300  # Maximum reliable with 4 GPUs and 20hrs
log_every_n_steps: 100
early_stopping_patience: 800

optimizer:
  lr: 1e-3

scheduler:
  instance:
    max_lr: 1e-3
    pct_start: 0.05
    final_div_factor: 100