defaults:
- dataset: ens10_prebatch
- model: mlp
- distribution: bernstein
- optimizer: adam
- scheduler: reduce_lr_plateau
- _self_

timeout_min: 1200

batch_size:  # Use prebatched dataset.
max_epochs: 3000
log_every_n_steps: 100
early_stopping_patience: 800

variable_idx: 0
n_variables: 1

optimizer:
  lr: 5e-4

distribution:
  mapping:
    predict_wind: False


model:
  n_variables: 1