defaults:
- dataset: gdps_prebatch_24h
- model: linear
- distribution: deterministic
- optimizer: adam
- scheduler: one_cycle
- _self_

timeout_min: 1200

batch_size:  # Use prebatched dataset.
max_epochs: 1000
log_every_n_steps: 100
early_stopping_patience: 150

variable_idx: 0
n_variables: 1

optimizer:
  lr: 1e-3

#scheduler:
#  instance:
#    patience: 50


# scheduler:
#   instance:
#     max_lr: 5e-5
#     pct_start: 0.05
#     final_div_factor: 10

distribution:
  mapping:
    predict_wind: False


model:
  n_variables: 1