defaults:
- dataset: pp2023_medium
- model: linear
- distribution: deterministic
- optimizer: adam
- scheduler: reduce_lr_plateau
- _self_

timeout_min: 120

batch_size: 64
max_epochs: 300
log_every_n_steps: 1
early_stopping_patience: 50

optimizer:
  lr: 1e-3

dataset:
  n_features: 8

scheduler:
  patience: 10
