defaults:
- dataset: ens10_hdf
- model: mlp_concat
- distribution: emos
- optimizer: adam
- scheduler: one_cycle
- _self_

timeout_min: 240

batch_size: 64
max_epochs: 100
log_every_n_steps: 100
early_stopping_patience: 500

variable_idx: 0
n_variables: 1

optimizer:
  lr:
    5e-4

distribution:
  mapping:
    predict_wind: False   
    use_std_prior: True

model:
  use_forecast_time_feature: False
  n_variables: 1