defaults:
- dataset: gdps_hdf_24h_onestep
- model: mlp
- distribution: emos
- optimizer: adam
- scheduler: one_cycle
- _self_

timeout_min: 480

batch_size: 64
max_epochs: 100
log_every_n_steps: 100
early_stopping_patience: 500

variable_idx: 0
n_variables: 1

optimizer:
  lr:
    5e-4

distribution:
  mapping:
    predict_wind: False

dataset:
  maker:
    step_idx: ???

model:
  use_step_embedding: False
  use_step_feature: False
  n_variables: 1